
#include "NvOnnxParser.h"
#include "common/common.h"
#include "common/logger.h"
#include "common/trtUtils.h"
#include <NvInfer.h>
#include <cstdlib>
#include <dlfcn.h>
#include <fstream>
#include <getopt.h>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>

struct VLMBuildArgs
{
    bool help{false};
    std::string llmOnnxPath;
    std::string visualOnnxPath;
    std::string llmEnginePath;
    std::string visualEnginePath;
    std::string modelType{"qwen2_vl"};
    int64_t maxInputLen{1024};
    int64_t maxSeqLen{4096};
    int64_t batchSize{1};
    int64_t imageTokens{512};
    bool dynamicShape{false};
    int64_t maxBatchSize{4};
    int64_t minImageTokens{4};
    int64_t maxImageTokens{1024};
    bool debug{false};
    bool visualOnly{false};
    bool llmOnly{false};
};

void printUsage(char const* programName)
{
    std::cerr
        << "Usage: " << programName
        << " [-h] <--llmOnnxPath str> <--visualOnnxPath str> <--llmEnginePath str> <--visualEnginePath str> [-b or "
           "--batchSize int] [-c or --maxInputLen int] [-s or --maxSeqLen int] [--dynamicShape] [--maxBatchSize int] "
           "[--debug] [--visualOnly] [--llmOnly]"
           "[--imageTokens int] [--minImageTokens int] [--maxImageTokens int] [--modelType str]"
        << std::endl;
    std::cerr << "Options:" << std::endl;
    std::cerr << "  -h                 Display this help message" << std::endl;
    std::cerr << "  --llmOnnxPath      Provide the input onnx file path for LLM. Required. " << std::endl;
    std::cerr << "  --visualOnnxPath   Provide the input onnx file path for visual encoder. Required. " << std::endl;
    std::cerr << "  --llmEnginePath    Provide the output TensorRT engine file path for LLM. Required. " << std::endl;
    std::cerr << "  --visualEnginePath Provide the output TensorRT engine file path for LLM. Required. " << std::endl;
    std::cerr << "  --batchSize        Provide the desired batch_size for builder. Default = 1" << std::endl;
    std::cerr << "  --maxBatchSize     Provide the maximum batch_size for builder. Default = 4" << std::endl;
    std::cerr << "  --maxInputLen      Provide the maximum input length for the model. Default = 128" << std::endl;
    std::cerr
        << "  --maxSeqLen        Provide the maximum output length for the model (including the input). Default = 4096"
        << std::endl;
    std::cerr << "  --dynamicShape     Use dynamic shape profiles." << std::endl;
    std::cerr << "  --debug            Use debug mode, which outputs more logs." << std::endl;
    std::cerr << "  --visualOnly       Only build Visual Engine." << std::endl;
    std::cerr << "  --llmOnly          Only build LLM Decoder Engine." << std::endl;
    std::cerr << "  --modelType        Provide the VLM model type, choose from [qwen2_vl]. Required." << std::endl;
    std::cerr
        << "  --imageTokens      Provide the total image tokens generated by ViT models for VLM. It's required when "
           "specified static shape. Default = 888"
        << std::endl;
    std::cerr << "  --minImageTokens   Provide the minimum total image tokens generated by ViT models for VLM. It's "
                 "required when specified dynamic shape. Default = 128"
              << std::endl;
    std::cerr << "  --maxImageTokens   Provide the maximum total image tokens generated by ViT models for VLM. It's "
                 "required when specified dynamic shape. Default = 5184"
              << std::endl;
}

bool parseVLMBuildArgs(VLMBuildArgs& args, int argc, char* argv[])
{
    static struct option long_options[]
        = {{"help", no_argument, 0, 'h'}, {"debug", no_argument, 0, 'd'}, {"visualOnly", no_argument, 0, 'V'},
            {"llmOnly", no_argument, 0, 'L'}, {"llmOnnxPath", required_argument, 0, 'i'},
            {"llmEnginePath", required_argument, 0, 'o'}, {"visualOnnxPath", required_argument, 0, 'I'},
            {"visualEnginePath", required_argument, 0, 'O'}, {"batchSize", required_argument, 0, 'b'},
            {"maxBatchSize", required_argument, 0, 'B'}, {"maxInputLen", required_argument, 0, 'c'},
            {"maxSeqLen", required_argument, 0, 's'}, {"dynamicShape", no_argument, 0, 'y'},
            {"imageTokens", required_argument, 0, 'M'}, {"minImageTokens", required_argument, 0, 't'},
            {"maxImageTokens", required_argument, 0, 'T'}, {"modelType", required_argument, 0, 'm'}, {0, 0, 0, 0}};

    int opt;
    // Loop to process each option
    int option_index = 0;
    while ((opt = getopt_long(argc, argv, "hi:o:I:O:b:c:s:M:m:T:t:dy", long_options, &option_index)) != -1)
    {
        switch (opt)
        {
        case 'h': args.help = true; return true;
        case 'V': args.visualOnly = true; break;
        case 'L': args.llmOnly = true; break;
        case 'i':
            if (optarg)
            {
                args.llmOnnxPath = optarg;
            }
            else
            {
                LOG_ERROR("--llmOnnxPath requires option argument.");
                return false;
            }
            break;
        case 'o':
            if (optarg)
            {
                args.llmEnginePath = optarg;
            }
            else
            {
                LOG_ERROR("--llmEnginePath requires option argument.");
                return false;
            }
            break;
        case 'I':
            if (optarg)
            {
                args.visualOnnxPath = optarg;
            }
            else
            {
                LOG_ERROR("--visualOnnxPath requires option argument.");
                return false;
            }
            break;
        case 'O':
            if (optarg)
            {
                args.visualEnginePath = optarg;
            }
            else
            {
                LOG_ERROR("--visualEnginePath requires option argument.");
                return false;
            }
            break;
        case 'b':
            if (optarg)
            {
                args.batchSize = std::stoi(optarg);
            }
            break;
        case 'B':
            if (optarg)
            {
                args.maxBatchSize = std::stoi(optarg);
            }
            break;
        case 'c':
            if (optarg)
            {
                args.maxInputLen = std::stoi(optarg);
            }
            break;
        case 's':
            if (optarg)
            {
                args.maxSeqLen = std::stoi(optarg);
            }
            break;
        case 'd': args.debug = true; break;
        case 'y': args.dynamicShape = true; break;
        case 't':
            if (optarg)
            {
                args.minImageTokens = std::stoi(optarg);
            }
            break;
        case 'T':
            if (optarg)
            {
                args.maxImageTokens = std::stoi(optarg);
            }
            break;
        case 'M':
            if (optarg)
            {
                args.imageTokens = std::stoi(optarg);
            }
            break;
        case 'm':
            if (optarg)
            {
                args.modelType = optarg;
            }
            else
            {
                LOG_ERROR("ERROR: model type requires option argument.");
                return false;
            }
            break;

        default: LOG_ERROR("ERROR: Invalid Argument %c is %s", opt, optarg); return false;
        }
    }
    return true;
}

std::string generateLLMTRTExecCommand(VLMBuildArgs const& args, int64_t const& numKVHeads,
    int64_t const& hiddenSizePerHead, int64_t const& imageHiddenSize, int64_t const& mropeDim)
{
    int64_t minInputLen = args.maxInputLen;
    int64_t optInputLen = args.maxInputLen;
    int64_t maxInputLen = args.maxInputLen;
    int64_t optBatchSize = args.batchSize;
    int64_t minBatchSize, maxBatchSize;
    int64_t minImageTokens, optImageTokens, maxImageTokens;
    if (args.dynamicShape)
    {
        minInputLen = 1;
        optInputLen = maxInputLen / 2;
        minBatchSize = 1;
        maxBatchSize = args.maxBatchSize;
        minImageTokens = args.minImageTokens;
        maxImageTokens = args.maxImageTokens;
        optImageTokens = (minImageTokens + maxImageTokens) / 2;
    }
    else
    {
        minBatchSize = args.batchSize;
        maxBatchSize = args.batchSize;
        minImageTokens = args.imageTokens;
        maxImageTokens = args.imageTokens;
        optImageTokens = args.imageTokens;
    }

    int64_t maxLength = args.maxSeqLen;

    std::string trtExecCommand = fmtstr(
        "Equivalent trtexec command: trtexec --onnx=%s --saveEngine=%s --staticPlugins=${PLUGIN_PATH} --stronglyTyped "
        "--verbose "
        "--profile=0 "
        "--minShapes=input_ids:%ldx%ld,context_lengths:%ld,last_token_ids:%ld*1,past_key_values.*:%ldx2x%ldx0x%ld,"
        "image_"
        "embeds:%ldx%ld,mrope_rotary_cos_sin:%ldx%ld,mrope_position_deltas:%ldx1 "
        "--optShapes=input_ids:%ldx%ld,context_lengths:%ld,last_token_ids:%ld*1,past_key_values.*:%ldx2x%ldx0x%ld,"
        "image_"
        "embeds:%ldx%ld,mrope_rotary_cos_sin:%ldx%ld,mrope_position_deltas:%ldx1 "
        "--maxShapes=input_ids:%ldx%ld,context_lengths:%ld,last_token_ids:%ld*1,past_key_values.*:%ldx2x%ldx0x%ld,"
        "image_"
        "embeds:%ldx%ld,mrope_rotary_cos_sin:%ldx%ld,mrope_position_deltas:%ldx1 "
        "--profile=1 "
        "--minShapes=input_ids:%ldx1,context_lengths:%ld,last_token_ids:%ld*1,past_key_values.*:%ldx2x%ldx%ldx%ld,"
        "image_"
        "embeds:%ldx%ld,mrope_rotary_cos_sin:%ldx%ld,mrope_position_deltas:%ldx1 "
        "--optShapes=input_ids:%ldx1,context_lengths:%ld,last_token_ids:%ld*1,past_key_values.*:%ldx2x%ldx%ldx%ld,"
        "image_"
        "embeds:%ldx%ld,mrope_rotary_cos_sin:%ldx%ld,mrope_position_deltas:%ldx1 "
        "--maxShapes=input_ids:%ldx1,context_lengths:%ld,last_token_ids:%ld*1,past_key_values.*:%ldx2x%ldx%ldx%ld,"
        "image_"
        "embeds:%ldx%ld,mrope_rotary_cos_sin:%ldx%ld,mrope_position_deltas:%ldx1",
        args.llmOnnxPath.c_str(), args.llmEnginePath.c_str(), minBatchSize, minInputLen, minBatchSize, minBatchSize,
        minBatchSize, numKVHeads, hiddenSizePerHead, minImageTokens, imageHiddenSize, minBatchSize, mropeDim,
        minBatchSize, optBatchSize, optInputLen, optBatchSize, optBatchSize, optBatchSize, numKVHeads,
        hiddenSizePerHead, optImageTokens, imageHiddenSize, optBatchSize, mropeDim, optBatchSize, maxBatchSize,
        maxInputLen, maxBatchSize, maxBatchSize, maxBatchSize, numKVHeads, hiddenSizePerHead, maxImageTokens,
        imageHiddenSize, maxBatchSize, mropeDim, maxBatchSize, minBatchSize, minBatchSize, minBatchSize, minBatchSize,
        numKVHeads, maxLength, hiddenSizePerHead, minImageTokens, imageHiddenSize, minBatchSize, mropeDim, minBatchSize,
        optBatchSize, optBatchSize, optBatchSize, optBatchSize, numKVHeads, maxLength, hiddenSizePerHead,
        optImageTokens, imageHiddenSize, optBatchSize, mropeDim, optBatchSize, maxBatchSize, maxBatchSize, maxBatchSize,
        maxBatchSize, numKVHeads, maxLength, hiddenSizePerHead, maxImageTokens, imageHiddenSize, maxBatchSize, mropeDim,
        maxBatchSize);
    return trtExecCommand;
}

int buildLLM(VLMBuildArgs const& args)
{
    int64_t optBatchSize = args.batchSize;
    int64_t minBatchSize, maxBatchSize;
    int64_t minImageTokens, optImageTokens, maxImageTokens;
    if (args.dynamicShape)
    {
        minBatchSize = 1;
        maxBatchSize = args.maxBatchSize;
        minImageTokens = args.minImageTokens;
        maxImageTokens = args.maxImageTokens;
        optImageTokens = (minImageTokens + maxImageTokens) / 2;
    }
    else
    {
        minBatchSize = args.batchSize;
        maxBatchSize = args.batchSize;
        minImageTokens = args.imageTokens;
        optImageTokens = args.imageTokens;
        maxImageTokens = args.imageTokens;
    }

    // Create the builder
    auto builder = std::unique_ptr<nvinfer1::IBuilder>(nvinfer1::createInferBuilder(gLogger));
    if (!builder)
    {
        LOG_ERROR("Failed to create builder.");
        return EXIT_FAILURE;
    }

    // Create the network definition
    auto const stronglyTyped = 1U << static_cast<uint32_t>(nvinfer1::NetworkDefinitionCreationFlag::kSTRONGLY_TYPED);
    auto network = std::unique_ptr<nvinfer1::INetworkDefinition>(builder->createNetworkV2(stronglyTyped));
    if (!network)
    {
        LOG_ERROR("Failed to create network.");
        return EXIT_FAILURE;
    }

    // Create the ONNX parser
    auto parser = std::unique_ptr<nvonnxparser::IParser>(nvonnxparser::createParser(*network, gLogger));
    if (!parser)
    {
        LOG_ERROR("Failed to create parser.");
        return EXIT_FAILURE;
    }

    // Parse the ONNX model
    if (!parser->parseFromFile(args.llmOnnxPath.c_str(), static_cast<int>(nvinfer1::ILogger::Severity::kWARNING)))
    {
        LOG_ERROR("Failed to parse ONNX file: %s", args.llmOnnxPath.c_str());
        return EXIT_FAILURE;
    }

    // Add optimization profile
    auto config = std::unique_ptr<nvinfer1::IBuilderConfig>(builder->createBuilderConfig());
    if (!config)
    {
        LOG_ERROR("Failed to create builder config.");
        return EXIT_FAILURE;
    }

    int32_t const nbInputs = network->getNbInputs();
    auto* contextProfile = builder->createOptimizationProfile();
    auto* generationProfile = builder->createOptimizationProfile();

    // Look for KV Cache
    int64_t nbKVCacheInputs = 0;
    nvinfer1::Dims kvDims;
    bool getKvDims = false;
    for (size_t i = 0; i < network->getNbInputs(); ++i)
    {
        if (network->getInput(i)->getDimensions().nbDims == 5)
        {
            ++nbKVCacheInputs;
            if (!getKvDims)
            {
                kvDims = network->getInput(i)->getDimensions();
                getKvDims = true;
            }
        }
    }
    if (nbKVCacheInputs == 0)
    {
        LOG_ERROR("Cannot find KV Cache input. KV Cache is guaranteed to have 5 dimensions in Plugin network!");
        return EXIT_FAILURE;
    }
    int64_t numKVHeads = kvDims.d[2];
    int64_t hiddenSizePerHead = kvDims.d[4];

    // set dimensions for input tensors. Only context phase input can possibly be dynamic
    bool result = true;

    if (args.dynamicShape)
    {
        result &= setOptimizationProfile(contextProfile, "input_ids", createDims({minBatchSize, 1}),
            createDims({optBatchSize, args.maxInputLen / 2}), createDims({maxBatchSize, args.maxInputLen}));
    }
    else
    {
        // Set static shape
        result &= setOptimizationProfile(contextProfile, "input_ids", createDims({optBatchSize, args.maxInputLen}),
            createDims({optBatchSize, args.maxInputLen}), createDims({optBatchSize, args.maxInputLen}));
    }
    result &= setOptimizationProfile(contextProfile, "context_lengths", createDims({minBatchSize}),
        createDims({optBatchSize}), createDims({maxBatchSize}));
    result &= setOptimizationProfile(contextProfile, "last_token_ids", createDims({minBatchSize, 1}),
        createDims({optBatchSize, 1}), createDims({maxBatchSize, 1}));
    result &= setOptimizationProfile(generationProfile, "input_ids", createDims({minBatchSize, 1}),
        createDims({optBatchSize, 1}), createDims({maxBatchSize, 1}));
    result &= setOptimizationProfile(generationProfile, "context_lengths", createDims({minBatchSize}),
        createDims({optBatchSize}), createDims({maxBatchSize}));
    result &= setOptimizationProfile(generationProfile, "last_token_ids", createDims({minBatchSize, 1}),
        createDims({optBatchSize, 1}), createDims({maxBatchSize, 1}));

    // Plugin does not have any dynamic shape.
    nvinfer1::Dims minKVContextShape = createDims({minBatchSize, 2, numKVHeads, 0, hiddenSizePerHead});
    nvinfer1::Dims optKVContextShape = createDims({optBatchSize, 2, numKVHeads, 0, hiddenSizePerHead});
    nvinfer1::Dims maxKVContextShape = createDims({maxBatchSize, 2, numKVHeads, 0, hiddenSizePerHead});
    nvinfer1::Dims minKVGenerationShape = createDims({minBatchSize, 2, numKVHeads, args.maxSeqLen, hiddenSizePerHead});
    nvinfer1::Dims optKVGenerationShape = createDims({optBatchSize, 2, numKVHeads, args.maxSeqLen, hiddenSizePerHead});
    nvinfer1::Dims maxKVGenerationShape = createDims({maxBatchSize, 2, numKVHeads, args.maxSeqLen, hiddenSizePerHead});

    for (int i = 0; i < nbKVCacheInputs; ++i)
    {
        result &= setOptimizationProfile(contextProfile, fmtstr("past_key_values.%d", i).c_str(), minKVContextShape,
            optKVContextShape, maxKVContextShape);
        result &= setOptimizationProfile(generationProfile, fmtstr("past_key_values.%d", i).c_str(),
            minKVGenerationShape, optKVGenerationShape, maxKVGenerationShape);
    }
    int imageHiddenSize = 0;
    int mropeDim = 0;
    for (int idx = 0; idx < nbInputs; idx++)
    {

        if (strcmp(network->getInput(idx)->getName(), "image_embeds") == 0)
        {
            imageHiddenSize = network->getInput(idx)->getDimensions().d[1];
        }
        else if (strcmp(network->getInput(idx)->getName(), "mrope_rotary_cos_sin") == 0)
        {
            mropeDim = network->getInput(idx)->getDimensions().d[1];
        }
    }
    if (imageHiddenSize == 0 || mropeDim == 0)
    {
        LOG_ERROR("Please add image_embeds and mrope_rotary_sin_cos as inputs for Qwen2-VL.");
    }

    result &= setOptimizationProfile(contextProfile, "image_embeds", createDims({minImageTokens, imageHiddenSize}),
        createDims({optImageTokens, imageHiddenSize}), createDims({maxImageTokens, imageHiddenSize}));
    result &= setOptimizationProfile(generationProfile, "image_embeds", createDims({1, imageHiddenSize}),
        createDims({1, imageHiddenSize}), createDims({1, imageHiddenSize}));

    result &= setOptimizationProfile(contextProfile, "mrope_rotary_cos_sin", createDims({minBatchSize, mropeDim}),
        createDims({optBatchSize, mropeDim}), createDims({maxBatchSize, mropeDim}));
    result &= setOptimizationProfile(contextProfile, "mrope_position_deltas", createDims({minBatchSize, 1}),
        createDims({optBatchSize, 1}), createDims({maxBatchSize, 1}));

    result &= setOptimizationProfile(generationProfile, "mrope_rotary_cos_sin", createDims({minBatchSize, mropeDim}),
        createDims({optBatchSize, mropeDim}), createDims({maxBatchSize, mropeDim}));
    result &= setOptimizationProfile(generationProfile, "mrope_position_deltas", createDims({minBatchSize, 1}),
        createDims({optBatchSize, 1}), createDims({maxBatchSize, 1}));

    if (!result)
    {
        LOG_ERROR("There are issues setting up optimization profiles.");
        return EXIT_FAILURE;
    }

    config->addOptimizationProfile(contextProfile);
    config->addOptimizationProfile(generationProfile);
    auto engine = builder->buildSerializedNetwork(*network, *config);

    if (!engine)
    {
        LOG_ERROR("Failed to build LLM engine.");
        return EXIT_FAILURE;
    }
    std::string folderPath = extractFolderName(args.llmEnginePath);
    if (folderPath != "")
    {
        if (!std::filesystem::exists(folderPath))
        {
            if (std::filesystem::create_directories(folderPath))
            {
                LOG_INFO("Created directory %s for saving LLM engine.", folderPath.c_str());
            }
            else
            {
                LOG_INFO("Failed to create directory %s for saving LLM engine.", folderPath.c_str());
            }
        }
    }
    std::ofstream ofs(args.llmEnginePath, std::ios::out | std::ios::binary);
    if (!ofs)
    {
        LOG_ERROR("Failed to open file for writing: %s", args.llmEnginePath.c_str());
        return EXIT_FAILURE;
    }
    ofs.write(static_cast<char*>(engine->data()), engine->size());
    ofs.close();
    LOG_INFO("Engine saved to %s", args.llmEnginePath.c_str());
    LOG_INFO(generateLLMTRTExecCommand(args, numKVHeads, hiddenSizePerHead, imageHiddenSize, mropeDim).c_str());

    return EXIT_SUCCESS;
}

std::string generateViTTRTExecCommand(VLMBuildArgs const& args, int64_t const& patchSize, int64_t const& ropeEmbdSize,
    int64_t const& minHW, int64_t const& optHW, int64_t const& maxHW)
{
    std::string trtExecCommand = fmtstr(
        "Equivalent ViT trtexec command: trtexec --onnx=%s --saveEngine=%s --stronglyTyped --verbose "
        "--minShapes=input:%ldx%ld,rotary_pos_emb:%ldx%ld,attention_mask:1x%ldx%ld "
        "--optShapes=input:%ldx%ld,rotary_pos_emb:%ldx%ld,attention_mask:1x%ldx%ld "
        "--maxShapes=input:%ldx%ld,rotary_pos_emb:%ldx%ld,attention_mask:1x%ldx%ld ",
        args.visualOnnxPath.c_str(), args.visualEnginePath.c_str(), minHW, patchSize, minHW, ropeEmbdSize, minHW, minHW,
        optHW, patchSize, optHW, ropeEmbdSize, optHW, optHW, maxHW, patchSize, maxHW, ropeEmbdSize, maxHW, maxHW);
    return trtExecCommand;
}

int buildViT(VLMBuildArgs const& args)
{
    int64_t minHW, optHW, maxHW;
    if (args.dynamicShape)
    {
        // In Qwen2-VL, HW is always 4ximageTokens because it equals to spatial_merge_size ** 2.
        minHW = args.minImageTokens * 4;
        maxHW = args.maxImageTokens * 4;
        optHW = (minHW + maxHW) / 2;
    }
    else
    {
        minHW = args.imageTokens * 4;
        optHW = minHW;
        maxHW = minHW;
    }

    // Create the builder
    auto builder = std::unique_ptr<nvinfer1::IBuilder>(nvinfer1::createInferBuilder(gLogger));
    if (!builder)
    {
        LOG_ERROR("Failed to create builder.");
        return EXIT_FAILURE;
    }

    // Create the network definition
    auto const stronglyTyped = 1U << static_cast<uint32_t>(nvinfer1::NetworkDefinitionCreationFlag::kSTRONGLY_TYPED);
    auto network = std::unique_ptr<nvinfer1::INetworkDefinition>(builder->createNetworkV2(stronglyTyped));
    if (!network)
    {
        LOG_ERROR("Failed to create network.");
        return EXIT_FAILURE;
    }

    // Create the ONNX parser
    auto parser = std::unique_ptr<nvonnxparser::IParser>(nvonnxparser::createParser(*network, gLogger));
    if (!parser)
    {
        LOG_ERROR("Failed to create parser.");
        return EXIT_FAILURE;
    }

    // Parse the ONNX model
    if (!parser->parseFromFile(args.visualOnnxPath.c_str(), static_cast<int>(nvinfer1::ILogger::Severity::kWARNING)))
    {
        LOG_ERROR("Failed to parse ONNX file: %s", args.visualOnnxPath.c_str());
        return EXIT_FAILURE;
    }

    // Add optimization profile
    auto config = std::unique_ptr<nvinfer1::IBuilderConfig>(builder->createBuilderConfig());
    if (!config)
    {
        LOG_ERROR("Failed to create builder config.");
        return EXIT_FAILURE;
    }

    int32_t const nbInputs = network->getNbInputs();
    auto* visualProfile = builder->createOptimizationProfile();
    int64_t patchSize = 0;
    int64_t ropeEmbdSize = 0;
    for (size_t i = 0; i < network->getNbInputs(); ++i)
    {
        if (strcmp(network->getInput(i)->getName(), "input") == 0)
        {
            patchSize = network->getInput(i)->getDimensions().d[1];
        }
        else if (strcmp(network->getInput(i)->getName(), "rotary_pos_emb") == 0)
        {
            ropeEmbdSize = network->getInput(i)->getDimensions().d[1];
        }
    }

    if ((patchSize == 0) || (ropeEmbdSize == 0))
    {
        LOG_ERROR("Cannot infer patchSize of RoPE Embed Size. Do you have proper ONNX inputs: input, rotary_pos_emb?");
        return EXIT_FAILURE;
    }

    // set dimensions for input tensors. Only context phase input can possibly be dynamic
    bool result = true;

    result &= setOptimizationProfile(visualProfile, "input", createDims({minHW, patchSize}),
        createDims({optHW, patchSize}), createDims({maxHW, patchSize}));
    result &= setOptimizationProfile(visualProfile, "rotary_pos_emb", createDims({minHW, ropeEmbdSize}),
        createDims({optHW, ropeEmbdSize}), createDims({maxHW, ropeEmbdSize}));
    result &= setOptimizationProfile(visualProfile, "attention_mask", createDims({1, minHW, minHW}),
        createDims({1, optHW, optHW}), createDims({1, maxHW, maxHW}));
    if (!result)
    {
        LOG_ERROR("Issues setting up optimization profile");
        return EXIT_FAILURE;
    }

    config->addOptimizationProfile(visualProfile);
    auto engine = builder->buildSerializedNetwork(*network, *config);

    if (!engine)
    {
        LOG_ERROR("Failed to build engine.");
        return EXIT_FAILURE;
    }
    std::string folderPath = extractFolderName(args.visualEnginePath);
    if (folderPath != "")
    {
        if (!std::filesystem::exists(folderPath))
        {
            if (std::filesystem::create_directories(folderPath))
            {
                LOG_INFO("Created directory %s for saving ViT engine.", folderPath.c_str());
            }
            else
            {
                LOG_INFO("Failed to create directory %s for saving ViT engine.", folderPath.c_str());
            }
        }
    }
    std::ofstream ofs(args.visualEnginePath, std::ios::out | std::ios::binary);
    if (!ofs)
    {
        LOG_ERROR("Failed to open file for writing: %s", args.visualEnginePath.c_str());
        return EXIT_FAILURE;
    }
    ofs.write(static_cast<char*>(engine->data()), engine->size());
    ofs.close();
    LOG_INFO("Engine saved to %s", args.visualEnginePath.c_str());
    LOG_INFO(generateViTTRTExecCommand(args, patchSize, ropeEmbdSize, minHW, optHW, maxHW).c_str());
    return EXIT_SUCCESS;
}

int main(int argc, char** argv)
{
    VLMBuildArgs args;
    if ((argc < 2) || (!parseVLMBuildArgs(args, argc, argv)))
    {
        LOG_ERROR("Unable to parse builder args.");
        printUsage(argv[0]);
        return EXIT_FAILURE;
    }
    if (args.help)
    {
        printUsage(argv[0]);
        return EXIT_SUCCESS;
    }

    if (args.debug)
    {
        gLogger.setLevel(nvinfer1::ILogger::Severity::kVERBOSE);
    }
    else
    {
        gLogger.setLevel(nvinfer1::ILogger::Severity::kINFO);
    }

    auto pluginHandles = loadPlugins();

    if (args.modelType != "qwen2_vl")
    {
        LOG_ERROR("Currently only QWen2-VL is supported for VLM.");
        return EXIT_FAILURE;
    }

    int status = EXIT_SUCCESS;
    bool isVisualBuild = true;
    bool isLLMBuild = true;
    if (args.visualOnly && args.llmOnly)
    {
        LOG_ERROR("--visualOnly and --llmOnly cannot both be true");
        return EXIT_FAILURE;
    }
    if (args.visualOnly)
    {
        LOG_INFO("Skipping LLM build.");
        isLLMBuild = false;
    }
    if (args.llmOnly)
    {
        LOG_INFO("SKipping Visual build");
        isVisualBuild = false;
    }

    if (isVisualBuild)
    {
        status = buildViT(args);
        if (status != EXIT_SUCCESS)
        {
            LOG_ERROR("Cannot build Visual Engine. Please check logs for detailed error message.");
            return status;
        }
    }
    if (isLLMBuild)
    {
        status = buildLLM(args);
        if (status != EXIT_SUCCESS)
        {
            LOG_ERROR("Cannot build Decoding LLM Engine. Please check logs for detailed error message.");
            return status;
        }
    }
    return status;
}