sonar.projectKey=EngHW_TensorRT-Edge-LLM_TensorRT-Edge-LLM_tensorrt-edge-llm
sonar.qualitygate.wait=true
sonar.sources=cpp,tensorrt_edgellm
sonar.exclusions=cpp/kernels/*/cubin/*
sonar.host.url=https://sonar.nvidia.com
sonar.python.version=3.8,3.9,3.10,3.11,3.12,3.13,3.14
sonar.sourceEncoding=utf-8
sonar.cfamily.reportingCppStandardOverride=c++17
sonar.cfamily.build-wrapper-output=bw-output
sonar.coverageReportPaths=build_coverage/sonarqube-coverage.xml
sonar.tests=tests,unittests
sonar.test.exclusions=tests/**,unittests/**
