#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2022-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Embed the XQA kernel sources into a C++ TU for NVRTC.

Derived from the generator that ships alongside the upstream XQA sources
(Apache-2.0; see README.md for the source commit).

Emits a single .cpp defining getXQAEmbeddedSources() -- see
cpp/kernels/decodeAttentionKernels/xqaEmbeddedSources.h. Every embedded file is
handed to nvrtcCreateProgram as a virtual header, so NVRTC compilation never
touches the filesystem.

Two things are load-bearing and easy to break:

  1. Each Entry carries an explicit ``include_name``, not a basename. NVRTC
     matches includeNames[] literally, and kernelSrcs/xqa/defines.h includes
     "common/cudaMacros.h" and
     "kernels/decodeAttentionKernels/xqaKernelTypes.h" by path. Registering
     those under their basename fails with
     'could not open source file "common/cudaMacros.h"'.
  2. File content is embedded as a raw string literal rather than escaped byte
     by byte. Same rodata either way, but the generated TU is ~5x smaller
     (1.2 MB vs 6.6 MB), which keeps the build tree and ccache sane.
"""

import argparse
import os
from collections import namedtuple
from pathlib import Path

# input_path: file to read from disk.
# include_name: the name NVRTC resolves #include against.
# var_name: identifier of the generated string literal.
Entry = namedtuple('Entry', ['input_path', 'include_name', 'var_name'])

# XQA kernel sources. mha.cu is the NVRTC entry point; the rest are virtual
# headers. Include names are bare because the XQA sources include each other
# that way.
XQA_FILES = [
    'mha.cu',
    'mha.h',
    'mha_components.cuh',
    'mha_stdheaders.cuh',
    'mhaUtils.cuh',
    'barriers.cuh',
    'cuda_hint.cuh',
    'defines.h',
    'ldgsts.cuh',
    'mma.cuh',
    'platform.h',
    'specDec.h',
    'utils.cuh',
    'utils.h',
]

MAIN_SOURCE = 'mha.cu'

# Project headers, registered under their path-prefixed include name.
PROJECT_HEADERS = [
    'common/cudaMacros.h',
    'kernels/decodeAttentionKernels/xqaKernelTypes.h',
]

# CUDA toolkit headers that the XQA translation unit reaches under NVRTC.
#
# This is a fixed list rather than a discovered one on purpose. Discovering it
# with `nvcc -E -Xcompiler -H` looks more robust but is not: nvcc force-injects
# `-include cuda_runtime.h`, and the host preprocessor emits no -H tree lines
# for command-line -include files, so the probe silently drops most of what it
# actually preprocessed. It also runs with __CUDACC_RTC__ *undefined* while
# NVRTC compiles with it defined, so the discovered set is neither a superset
# nor a subset of what NVRTC needs by construction.
#
# The list below is the transitive closure under __CUDACC_RTC__, verified by
# compiling every macro combination decoderXQAJitCompiler.cpp can emit. Note
# vector_types.h / vector_functions.h / device_types.h are deliberately absent:
# cuda_fp16.h and friends skip those under __CUDACC_RTC__.
REQUIRED_CUDA_HEADERS = [
    'cuda_bf16.h',
    'cuda_bf16.hpp',
    'cuda_fp16.h',
    'cuda_fp16.hpp',
]

# cpp/common/cudaMacros.h includes cuda_fp8.h only for CUDA >= 11.8 and
# cuda_fp4.h only for CUDA >= 12.8. cuda_fp4.h pulls cuda_fp6.h. The guards
# skip these includes on older toolkits, so their absence is not an error.
OPTIONAL_CUDA_HEADERS = [
    'cuda_fp8.h',
    'cuda_fp8.hpp',
    'cuda_fp4.h',
    'cuda_fp4.hpp',
    'cuda_fp6.h',
    'cuda_fp6.hpp',
]

PROLOGUE = '''// Auto-generated by kernelSrcs/xqa/gen_cpp_header.py -- do not edit.
#include "kernels/decodeAttentionKernels/xqaEmbeddedSources.h"

namespace trt_edgellm
{
namespace
{

'''

EPILOGUE = '''} // namespace trt_edgellm
'''


def to_identifier(name):
    """Turn a file name or relative include path into a valid C++ identifier."""
    return ''.join(c if c.isalnum() else '_' for c in name)


def to_raw_string_literal(content, path):
    """Wrap file content in a raw string literal, picking a non-colliding delimiter."""
    for delimiter in ('xqa_embed', 'xqa_embed2', 'xqa_embed3'):
        if ')' + delimiter not in content:
            return 'R"{d}({c}){d}"'.format(d=delimiter, c=content)
    raise RuntimeError(
        '{}: content collides with every raw string delimiter'.format(path))


def collect_entries(xqa_dir, cpp_dir, cuda_include_dir):
    """Resolve every embedded file to an (input_path, include_name, var_name)."""
    entries = []

    for name in XQA_FILES:
        entries.append(
            Entry(input_path=os.path.join(xqa_dir, name),
                  include_name=name,
                  var_name='kSrc_' + to_identifier(name)))

    for rel_path in PROJECT_HEADERS:
        entries.append(
            Entry(input_path=os.path.join(cpp_dir, rel_path),
                  include_name=rel_path,
                  var_name='kSrc_' + to_identifier(rel_path)))

    for name in REQUIRED_CUDA_HEADERS:
        entries.append(
            Entry(input_path=os.path.join(cuda_include_dir, name),
                  include_name=name,
                  var_name='kSrc_cuda_' + to_identifier(name)))

    for name in OPTIONAL_CUDA_HEADERS:
        path = os.path.join(cuda_include_dir, name)
        if not os.path.exists(path):
            print('note: optional CUDA header not present, skipping: ' + path)
            continue
        entries.append(
            Entry(input_path=path,
                  include_name=name,
                  var_name='kSrc_cuda_' + to_identifier(name)))

    # Post-condition. A mis-pointed --cuda_include_dir (easy to do on a cross
    # build, where the target sysroot and the host toolkit differ) would
    # otherwise produce a plausible-looking TU that can never JIT anything.
    missing = [
        e.input_path for e in entries if not os.path.exists(e.input_path)
    ]
    if missing:
        raise SystemExit('error: embedded source(s) not found:\n  ' +
                         '\n  '.join(missing))

    return entries


def generate(entries):
    out = [PROLOGUE]
    main_var = None

    for entry in entries:
        with open(entry.input_path, 'r') as f:
            content = f.read()
        out.append('static char const {}[] = {};\n\n'.format(
            entry.var_name, to_raw_string_literal(content, entry.input_path)))
        if entry.include_name == MAIN_SOURCE:
            main_var = entry.var_name

    if main_var is None:
        raise SystemExit(
            'error: main source {} was not embedded'.format(MAIN_SOURCE))

    out.append('} // namespace\n\n')
    out.append('XQAEmbeddedSources const& getXQAEmbeddedSources()\n{\n')
    out.append('    static XQAEmbeddedSources const instance{\n')
    out.append('        {},\n'.format(main_var))
    out.append('        {\n')
    for entry in entries:
        if entry.include_name == MAIN_SOURCE:
            continue
        out.append('            {{"{}", {}}},\n'.format(
            entry.include_name, entry.var_name))
    out.append('        }\n')
    out.append('    };\n')
    out.append('    return instance;\n')
    out.append('}\n\n')
    out.append(EPILOGUE)

    return ''.join(out)


def main():
    parser = argparse.ArgumentParser(
        description='Embed XQA kernel sources into a C++ TU for NVRTC.',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('-o',
                        '--output',
                        required=True,
                        help='generated .cpp path')
    parser.add_argument('--xqa_dir',
                        default=os.path.dirname(os.path.abspath(__file__)),
                        help='directory holding the XQA kernel sources')
    parser.add_argument('--cpp_dir',
                        required=True,
                        help='edge-llm cpp/ root, for the project headers')
    parser.add_argument('--cuda_include_dir',
                        required=True,
                        help='CUDA Toolkit include directory')
    args = parser.parse_args()

    entries = collect_entries(args.xqa_dir, args.cpp_dir,
                              args.cuda_include_dir)
    content = generate(entries)

    # Only rewrite on change so downstream objects are not needlessly rebuilt.
    output = Path(args.output)
    if output.exists() and output.read_text() == content:
        print('{} is up to date'.format(output))
        return

    output.parent.mkdir(parents=True, exist_ok=True)
    # Write via a temp file in the same directory + atomic rename: the output is
    # consumed by more than one target, so a partially written file must never
    # be observable.
    tmp = output.with_name(output.name + '.tmp{}'.format(os.getpid()))
    tmp.write_text(content)
    os.replace(str(tmp), str(output))
    print('Generated {} with {} embedded files'.format(output, len(entries)))


if __name__ == '__main__':
    main()
