# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""CI orchestration and generated-matrix support for wheel packaging."""

from __future__ import annotations

import json
import os
import platform
import shlex
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path, PurePosixPath
from typing import Dict, List, Mapping, Optional, Tuple

from . import assemble, base, source
from .config import (REPO_ROOT, load_matrix, required_environment, run_checked,
                     sha256, write_json)

_ABI_INTERPRETERS = {
    "cp310": "python3.10",
    "cp311": "python3.11",
    "cp312": "python3.12",
}
_GENERATED_CI = REPO_ROOT / ".gitlab" / "ci" / "wheel-generated.yml"
_MAX_NEEDED_JOB_NAME = 128
_UV_REQUIREMENT = "uv==0.8.14"
_TARGET_PYTHON_UBUNTU_RELEASE = {
    "3.10": "jammy",
    "3.11": "jammy",
    "3.12": "noble",
}
_BUILD_ENVIRONMENT = {
    "TRT_PACKAGE_DIR": "ci_trt_package",
    "WHEEL_TOOLCHAIN_FILE": "ci_toolchain",
    "WHEEL_TARGET_SYSROOT": "ci_sysroot",
    "WHEEL_TARGET_PYTHON_INCLUDE_ROOT": "ci_python_headers",
}
_REMOTE_INTEGRATION_ENVIRONMENT = {
    "REMOTE_TARGET": "ci_remote",
    "BOARD_IP": "ci_board_ip",
    "BOARD_USER": "ci_board_user",
    "WHEEL_TARGET_TRT_WHEEL": "ci_target_trt_wheel",
    "WHEEL_TARGET_MODEL_DIR": "ci_target_model_dir",
    "WHEEL_TARGET_WORK_DIR": "ci_target_work_dir",
}
_LOCAL_INTEGRATION_ENVIRONMENT = {
    "REMOTE_TARGET": "ci_remote",
    "TRT_PACKAGE_DIR": "ci_trt_package",
}


def _yaml_value(value: object) -> str:
    if isinstance(value, bool):
        return '"1"' if value else '"0"'
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _ci_row(row: Mapping[str, object], *, phase: str) -> List[str]:
    if phase == "build":
        runner = row["ci_build_runner"]
        image = row["ci_build_image"]
        runner_variable = "BUILD_RUNNER_TAG"
        image_variable = "BUILD_IMAGE"
    elif phase == "test":
        runner = row["ci_test_runner"]
        image = row["ci_test_image"]
        runner_variable = "TEST_RUNNER_TAG"
        image_variable = "TEST_IMAGE"
    else:
        raise ValueError(f"Unknown CI matrix phase {phase!r}.")
    values = {
        "VARIANT": row["variant_id"],
        runner_variable: runner,
        image_variable: image,
    }
    lines = ["      - PYTHON_ABI: [cp310, cp311, cp312]"]
    lines.extend(f"        {name}: {_yaml_value(value)}"
                 for name, value in values.items())
    return lines


def _validate_matrix_job_names(rows: List[Mapping[str, object]]) -> None:
    for row in rows:
        for job, runner_field, image_field in (
            ("wheel_native_payloads", "ci_build_runner", "ci_build_image"),
            ("wheel_integration", "ci_test_runner", "ci_test_image"),
        ):
            values = (row["variant_id"], row[runner_field], row[image_field])
            for python_abi in _ABI_INTERPRETERS:
                suffix = ", ".join(
                    str(value) for value in (python_abi, *values))
                name = f"{job}: [{suffix}]"
                if len(name) > _MAX_NEEDED_JOB_NAME:
                    raise RuntimeError(
                        f"Generated matrix job name exceeds "
                        f"{_MAX_NEEDED_JOB_NAME} characters: {name}")


def generated_ci() -> str:
    """Render concrete payload and integration matrices from variants.toml."""
    _, rows = load_matrix(REPO_ROOT / "packaging" / "variants.toml")
    _validate_matrix_job_names(rows)
    build_matrix = "\n".join(line for row in rows
                             for line in _ci_row(row, phase="build"))
    test_matrix = "\n".join(line for row in rows
                            for line in _ci_row(row, phase="test"))
    return f"""# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# Generated by: python packaging/wheel_cli.py generate-ci
# Do not edit this file directly.

wheel_native_payloads:
  extends: [.wheel_payload_template]
  parallel:
    matrix:
{build_matrix}

wheel_integration:
  extends: [.wheel_integration_template]
  parallel:
    matrix:
{test_matrix}
"""


def generate_ci(*, check: bool = False) -> None:
    """Write or validate the checked-in generated GitLab matrix."""
    rendered = generated_ci()
    if check:
        actual = (_GENERATED_CI.read_text(
            encoding="utf-8") if _GENERATED_CI.is_file() else "")
        if actual != rendered:
            raise RuntimeError(
                f"{_GENERATED_CI} is stale; run wheel_cli.py generate-ci.")
        return
    _GENERATED_CI.write_text(rendered, encoding="utf-8")


def _install_toolchain(python: str = sys.executable) -> None:
    pip = subprocess.run([python, "-m", "pip", "--version"],
                         text=True,
                         stdout=subprocess.DEVNULL,
                         stderr=subprocess.DEVNULL)
    if pip.returncode != 0:
        run_checked([python, "-m", "ensurepip", "--upgrade"])
    run_checked([
        python, "-m", "pip", "install", "--requirement",
        str(REPO_ROOT / "packaging" / "wheel-toolchain-requirements.txt")
    ],
                cwd=REPO_ROOT)


def _toolchain_python(python: str, python_abi: str) -> str:
    environment = REPO_ROOT / "venv" / f"wheel-{python_abi}"
    shutil.rmtree(environment, ignore_errors=True)
    run_checked([python, "-m", "venv", str(environment)])
    isolated_python = str(environment / "bin" / "python")
    _install_toolchain(isolated_python)
    return isolated_python


def _update_submodules() -> None:
    error = None
    for attempt in range(1, 4):
        try:
            run_checked(
                ["git", "submodule", "update", "--init", "--recursive"],
                cwd=REPO_ROOT)
            return
        except RuntimeError as current:
            error = current
            if attempt < 3:
                delay = 15 * attempt
                print(f"Submodule update failed; retrying in {delay}s.",
                      file=sys.stderr)
                time.sleep(delay)
    assert error is not None
    raise error


def precheck() -> None:
    """Validate source, matrix, generated CI, and exact submodules."""
    _update_submodules()
    _install_toolchain()
    source.main([
        "--output",
        str(REPO_ROOT / "artifacts" / "provenance" / "source.json")
    ])
    load_matrix(REPO_ROOT / "packaging" / "variants.toml")
    generate_ci(check=True)


def build_base_ci() -> None:
    """Build one scheduled Python base wheel."""
    python_abi = required_environment("PYTHON_ABI")
    actual = f"cp{sys.version_info.major}{sys.version_info.minor}"
    if actual != python_abi:
        raise RuntimeError(
            f"Scheduled ABI {python_abi} does not match interpreter {actual}.")
    _update_submodules()
    _install_toolchain()
    base.main([
        "--output-dir",
        str(REPO_ROOT / "artifacts" / "base" / python_abi),
    ])


def _python_for_abi(python_abi: str) -> str:
    try:
        interpreter = _ABI_INTERPRETERS[python_abi]
    except KeyError as error:
        raise RuntimeError(f"Unsupported Python ABI {python_abi}.") from error
    executable = shutil.which(interpreter)
    if executable is None:
        version = interpreter.removeprefix("python")
        candidates = sorted(
            Path("/usr/local/pyenv/versions").glob(f"{version}.*/bin/python"))
        if len(candidates) == 1:
            executable = os.fspath(candidates[0])
    if executable is None:
        raise RuntimeError(f"Required interpreter {interpreter} is missing.")
    return executable


def _managed_python(version: str) -> str:
    bootstrap = REPO_ROOT / "venv" / "python-bootstrap"
    bootstrap_python = bootstrap / "bin" / "python"
    uv = bootstrap / "bin" / "uv"
    if not uv.is_file():
        shutil.rmtree(bootstrap, ignore_errors=True)
        run_checked([sys.executable, "-m", "venv", str(bootstrap)])
        run_checked(
            [str(bootstrap_python), "-m", "pip", "install", _UV_REQUIREMENT])
    install_root = REPO_ROOT / "venv" / "managed-python"
    environment = dict(os.environ)
    environment["UV_PYTHON_INSTALL_DIR"] = str(install_root)
    run_checked([str(uv), "python", "install", version], env=environment)
    candidates = sorted(install_root.rglob(f"python{version}"))
    executables = [path for path in candidates if path.parent.name == "bin"]
    if len(executables) != 1:
        raise RuntimeError(
            f"Expected one managed Python {version}, found {executables}.")
    return str(executables[0])


def _install_host_python(version: str) -> str:
    executable = shutil.which(f"python{version}")
    if executable is not None:
        return executable
    if os.geteuid() != 0:
        return _managed_python(version)
    run_checked(["apt-get", "update"])
    run_checked([
        "apt-get", "install", "-y", "--no-install-recommends",
        "software-properties-common"
    ])
    run_checked(["add-apt-repository", "-y", "ppa:deadsnakes/ppa"])
    run_checked(["apt-get", "update"])
    run_checked([
        "apt-get", "install", "-y", "--no-install-recommends",
        f"python{version}", f"python{version}-dev", f"python{version}-venv"
    ])
    return _python_for_abi(f"cp{version.replace('.', '')}")


def _scope_deb_source_to_host(path: Path) -> None:
    if not path.is_file():
        return
    changed = False
    lines = []
    for line in path.read_text(encoding="utf-8").splitlines(keepends=True):
        stripped = line.lstrip()
        prefix = line[:len(line) - len(stripped)]
        if stripped.startswith("deb ") and not stripped.startswith("deb ["):
            line = prefix + "deb [arch=amd64] " + stripped.removeprefix("deb ")
            changed = True
        lines.append(line)
    if changed:
        path.write_text("".join(lines), encoding="utf-8")


def _scope_deb822_source_to_host(path: Path) -> None:
    if not path.is_file():
        return
    changed = False
    stanzas = []
    for stanza in path.read_text(encoding="utf-8").split("\n\n"):
        lines = stanza.splitlines()
        types_index = next((index for index, line in enumerate(lines)
                            if line.lower().startswith("types:")), None)
        has_architectures = any(line.lower().startswith("architectures:")
                                for line in lines)
        if types_index is not None and not has_architectures:
            lines.insert(types_index + 1, "Architectures: amd64")
            changed = True
        stanzas.append("\n".join(lines))
    if changed:
        path.write_text("\n\n".join(stanzas).rstrip() + "\n", encoding="utf-8")


def _install_target_python_headers(version: str, headers: Path) -> Path:
    target_config = (headers.parent / "aarch64-linux-gnu" / headers.name /
                     "pyconfig.h")
    if target_config.is_file():
        return headers
    for source in [
            Path("/etc/apt/sources.list"),
            *Path("/etc/apt/sources.list.d").glob("*.list")
    ]:
        _scope_deb_source_to_host(source)
    for source in Path("/etc/apt/sources.list.d").glob("*.sources"):
        _scope_deb822_source_to_host(source)
    try:
        target_release = _TARGET_PYTHON_UBUNTU_RELEASE[version]
    except KeyError as error:
        raise RuntimeError(
            f"No arm64 CPython header source is configured for {version}."
        ) from error
    # CPython extension ABI is stable within a minor release. Select an Ubuntu
    # release that publishes that minor for arm64, independently of the build image.
    ports = Path("/etc/apt/sources.list.d/ubuntu-ports-arm64.list")
    ports.write_text(
        "\n".join(f"deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports "
                  f"{release} main restricted universe multiverse"
                  for release in (target_release, f"{target_release}-updates",
                                  f"{target_release}-security")) + "\n",
        encoding="utf-8")
    run_checked(["dpkg", "--add-architecture", "arm64"])
    run_checked(["apt-get", "update"])
    target_root = Path(
        tempfile.gettempdir()) / f"edgellm-python{version}-arm64"
    target_root.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="edgellm-python-deb-") as value:
        download_dir = Path(value)
        download_dir.chmod(0o777)
        run_checked(["apt-get", "download", f"libpython{version}-dev:arm64"],
                    cwd=download_dir)
        packages = list(download_dir.glob("*.deb"))
        if len(packages) != 1:
            raise RuntimeError(
                f"Expected one target CPython development package: {packages}."
            )
        run_checked(
            ["dpkg-deb", "--extract",
             str(packages[0]),
             str(target_root)])
    include_root = target_root / "usr" / "include"
    staged_headers = include_root / headers.name
    target_link = staged_headers / "aarch64-linux-gnu"
    target_link.unlink(missing_ok=True)
    target_link.symlink_to(include_root / "aarch64-linux-gnu",
                           target_is_directory=True)
    staged_config = target_link / headers.name / "pyconfig.h"
    if not (staged_headers /
            "Python.h").is_file() or not staged_config.is_file():
        raise RuntimeError(
            f"Target CPython headers are incomplete under {staged_headers}.")
    return staged_headers


def _bootstrap_build_python(row: Mapping[str, object], python_abi: str) -> str:
    version = _ABI_INTERPRETERS[python_abi].removeprefix("python")
    build_python = _install_host_python(version)
    if row["ci_build_mode"] == "cross":
        header_template = str(row["ci_python_headers"])
        headers = Path(
            header_template.format(python_abi=python_abi,
                                   python_version=version))
        staged_headers = _install_target_python_headers(version, headers)
        os.environ["WHEEL_TARGET_PYTHON_INCLUDE_ROOT"] = str(staged_headers)
    return _toolchain_python(build_python, python_abi)


def _normalized_trt_package(trt_dir: Path) -> Path:
    if (trt_dir / "include" / "NvInfer.h").is_file():
        return trt_dir
    include_candidates = sorted((trt_dir / "include").glob("*/NvInfer.h"))
    library_candidates = sorted((trt_dir / "lib").glob("*/libnvinfer.so"))
    if len(include_candidates) != 1 or len(library_candidates) != 1:
        return trt_dir
    staged = REPO_ROOT / "artifacts" / "trt-packages" / _host_arch()
    shutil.rmtree(staged, ignore_errors=True)
    staged.mkdir(parents=True)
    (staged / "include").symlink_to(include_candidates[0].parent,
                                    target_is_directory=True)
    (staged / "lib").symlink_to(library_candidates[0].parent,
                                target_is_directory=True)
    return staged


def _variant_row(variant: str) -> Mapping[str, object]:
    _, rows = load_matrix(REPO_ROOT / "packaging" / "variants.toml")
    row = next((value for value in rows if value["variant_id"] == variant),
               None)
    if row is None:
        raise RuntimeError(f"Unknown scheduled variant {variant}.")
    return row


def _apply_variant_environment(row: Mapping[str, object],
                               fields: Mapping[str, str]) -> None:
    for variable, field in fields.items():
        value = row.get(field)
        if value is None or value == "":
            os.environ.pop(variable, None)
            continue
        if isinstance(value, bool):
            os.environ[variable] = "1" if value else "0"
            continue
        text = str(value)
        os.environ[variable] = (required_environment(text[1:])
                                if text.startswith("$") else text)


def _host_arch() -> str:
    machine = platform.machine().lower()
    return {"amd64": "x86_64", "arm64": "aarch64"}.get(machine, machine)


def _cross_arguments(row: Mapping[str, object], python_abi: str,
                     trt_dir: Path) -> Tuple[List[str], List[str]]:
    build_mode = row["ci_build_mode"]
    if build_mode == "native":
        if row["cpu_arch"] != _host_arch():
            raise RuntimeError(
                f"Native build for {row['variant_id']} requires a "
                f"{row['cpu_arch']} runner, found {_host_arch()}.")
        return [], []
    if row["cpu_arch"] == _host_arch():
        raise RuntimeError(
            f"Cross build for {row['variant_id']} requires a non-"
            f"{row['cpu_arch']} runner.")
    toolchain = Path(required_environment("WHEEL_TOOLCHAIN_FILE"))
    sysroot = Path(required_environment("WHEEL_TARGET_SYSROOT"))
    header_template = required_environment("WHEEL_TARGET_PYTHON_INCLUDE_ROOT")
    python_version = _ABI_INTERPRETERS[python_abi].removeprefix("python")
    headers = Path(
        header_template.format(python_abi=python_abi,
                               python_version=python_version))
    if not toolchain.is_file() or not sysroot.is_dir():
        raise RuntimeError(
            "The scheduled cross toolchain or sysroot is missing.")
    if not (headers / "Python.h").is_file():
        raise RuntimeError(f"Target Python headers are missing: {headers}.")
    return (
        [
            "--toolchain-file",
            str(toolchain),
            "--target-sysroot",
            str(sysroot),
            "--target-python-include-dir",
            str(headers),
        ],
        ["--dependency-root",
         str(sysroot), "--dependency-root",
         str(trt_dir)],
    )


def build_payload_ci() -> None:
    """Build and verify one scheduled native payload."""
    python_abi = required_environment("PYTHON_ABI")
    variant = required_environment("VARIANT")
    row = _variant_row(variant)
    _apply_variant_environment(row, _BUILD_ENVIRONMENT)
    python_bin = _bootstrap_build_python(row, python_abi)
    trt_dir = _normalized_trt_package(
        Path(required_environment("TRT_PACKAGE_DIR")).resolve())
    output = REPO_ROOT / "artifacts" / "payloads" / f"{variant}-{python_abi}"
    build_extra, verify_extra = _cross_arguments(row, python_abi, trt_dir)
    environment = dict(os.environ)
    environment["LD_LIBRARY_PATH"] = ":".join(
        value for value in (str(trt_dir / "lib"),
                            environment.get("LD_LIBRARY_PATH", "")) if value)
    _update_submodules()
    run_checked([
        python_bin,
        str(REPO_ROOT / "packaging" / "wheel_cli.py"),
        "prepare-cutedsl",
        "--variant",
        variant,
        "--artifact-dir",
        str(REPO_ROOT / "kernelSrcs" / "cuteDSLPrebuilt"),
    ],
                cwd=REPO_ROOT,
                env=environment)
    run_checked([
        python_bin,
        str(REPO_ROOT / "packaging" / "wheel_cli.py"),
        "build-payload",
        "--variant",
        variant,
        "--python-abi",
        python_abi,
        "--trt-package-dir",
        str(trt_dir),
        *build_extra,
        "--output-dir",
        str(output),
    ],
                cwd=REPO_ROOT,
                env=environment)
    run_checked([
        python_bin,
        str(REPO_ROOT / "packaging" / "wheel_cli.py"),
        "verify-payload",
        "--stage",
        str(output),
        *verify_extra,
    ],
                cwd=REPO_ROOT,
                env=environment)


def _single_wheel(cpu_arch: str, python_abi: str) -> Path:
    directory = REPO_ROOT / "dist" / cpu_arch / python_abi
    wheels = sorted(directory.glob("*.whl"))
    if len(wheels) != 1:
        raise RuntimeError(
            f"Expected one wheel under {directory}, found {len(wheels)}.")
    return wheels[0].resolve()


def assemble_ci() -> None:
    """Assemble and checksum one architecture/ABI wheel."""
    cpu_arch = required_environment("CPU_ARCH")
    python_abi = required_environment("PYTHON_ABI")
    _update_submodules()
    _install_toolchain()
    bases = sorted(
        (REPO_ROOT / "artifacts" / "base" / python_abi).glob("*.whl"))
    if len(bases) != 1:
        raise RuntimeError(f"Expected one {python_abi} base wheel.")
    output = REPO_ROOT / "dist" / cpu_arch / python_abi
    assemble.main([
        "--base-wheel",
        str(bases[0]),
        "--payload-root",
        str(REPO_ROOT / "artifacts" / "payloads"),
        "--cpu-arch",
        cpu_arch,
        "--python-abi",
        python_abi,
        "--output-dir",
        str(output),
    ])
    wheel = _single_wheel(cpu_arch, python_abi)
    (output / "wheel.sha256").write_text(f"{sha256(wheel)}  {wheel.name}\n",
                                         encoding="utf-8")


def _model_dir() -> Path:
    explicit = os.environ.get("WHEEL_MODEL_DIR")
    if explicit:
        return Path(explicit).resolve(strict=True)
    root = Path(required_environment("LLM_MODELS_DIR"))
    candidates = (
        root / "Qwen2.5-0.5B-Instruct",
        root / "Qwen" / "Qwen2.5-0.5B-Instruct",
    )
    for candidate in candidates:
        if candidate.is_dir():
            return candidate.resolve()
    raise RuntimeError(
        "Set WHEEL_MODEL_DIR to the Qwen2.5-0.5B-Instruct checkpoint.")


def _trt_python_wheel(trt_dir: Path, python_abi: str) -> Path:
    wheels = sorted(
        path
        for path in (trt_dir / "python").glob(f"tensorrt-*-{python_abi}-*.whl")
        if path.is_file())
    if len(wheels) != 1:
        raise RuntimeError(
            f"Expected one TensorRT {python_abi} wheel under {trt_dir / 'python'}."
        )
    return wheels[0].resolve()


def _gpu_uuid_for_sm(gpu_sm: int) -> str:
    explicit = os.environ.get("WHEEL_GPU_UUID")
    if explicit:
        return explicit
    try:
        result = subprocess.run([
            "nvidia-smi",
            "--query-gpu=uuid,compute_cap",
            "--format=csv,noheader,nounits",
        ],
                                check=True,
                                text=True,
                                stdout=subprocess.PIPE,
                                stderr=subprocess.PIPE)
    except (OSError, subprocess.CalledProcessError) as error:
        raise RuntimeError(
            "Cannot query GPU UUIDs for wheel qualification.") from error
    matches = []
    for line in result.stdout.splitlines():
        try:
            uuid, capability = (value.strip() for value in line.split(",", 1))
            major, minor = (int(value) for value in capability.split(".", 1))
        except ValueError as error:
            raise RuntimeError(
                f"Unexpected nvidia-smi GPU row: {line!r}.") from error
        if major * 10 + minor == gpu_sm:
            matches.append(uuid)
    if not matches:
        raise RuntimeError(f"No visible GPU reports required SM {gpu_sm}.")
    return sorted(matches)[0]


def _integration_environment(trt_dir: Path,
                             gpu_sm: Optional[int]) -> Dict[str, str]:
    environment = dict(os.environ)
    environment.pop("PYTHONPATH", None)
    environment.pop("LLM_SDK_DIR", None)
    environment["LD_LIBRARY_PATH"] = ":".join(
        value for value in (str(trt_dir / "lib"),
                            environment.get("LD_LIBRARY_PATH", "")) if value)
    if gpu_sm is not None:
        environment["CUDA_VISIBLE_DEVICES"] = _gpu_uuid_for_sm(gpu_sm)
    return environment


def _local_integration(row: Mapping[str, object], python_abi: str, wheel: Path,
                       result: Path) -> None:
    variant = str(row["variant_id"])
    version = _ABI_INTERPRETERS[python_abi].removeprefix("python")
    python_bin = _install_host_python(version)
    trt_dir = _normalized_trt_package(
        Path(required_environment("TRT_PACKAGE_DIR")).resolve())
    model_dir = _model_dir()
    environment = _integration_environment(trt_dir, int(row["gpu_sm"]))
    with tempfile.TemporaryDirectory(
            prefix="edgellm-wheel-test-") as temporary:
        root = Path(temporary)
        venv = root / "venv"
        run_checked([python_bin, "-m", "venv", str(venv)])
        interpreter = venv / "bin" / "python"
        run_checked(
            [str(interpreter), "-m", "pip", "install", "--upgrade", "pip"],
            env=environment)
        trt_requirement = row.get("ci_test_trt_requirement")
        if trt_requirement:
            trt_install = [
                str(interpreter),
                "-m",
                "pip",
                "install",
                "--extra-index-url",
                os.environ.get("WHEEL_EXTRA_INDEX_URL",
                               "https://pypi.nvidia.com"),
                str(trt_requirement),
            ]
        else:
            trt_install = [
                str(interpreter),
                "-m",
                "pip",
                "install",
                str(_trt_python_wheel(trt_dir, python_abi)),
            ]
        run_checked(trt_install, env=environment)
        install = [
            str(interpreter),
            "-m",
            "pip",
            "install",
            "--extra-index-url",
            os.environ.get("WHEEL_EXTRA_INDEX_URL", "https://pypi.nvidia.com"),
            str(wheel),
        ]
        run_checked(install, env=environment)
        raw_result = root / "result.json"
        run_checked([
            str(interpreter),
            "-I",
            str(REPO_ROOT / "examples" / "python" /
                "installed_wheel_build_and_infer.py"),
            str(model_dir),
            str(root / "engine"),
            "--expected-variant",
            variant,
            "--result",
            str(raw_result),
        ],
                    cwd=root,
                    env=environment)
        evidence = json.loads(raw_result.read_text(encoding="utf-8"))
    evidence.update({
        "variant_id": variant,
        "python_abi": python_abi,
        "wheel": wheel.name,
        "wheel_sha256": sha256(wheel),
    })
    write_json(result, evidence)


def _ssh_prefix(password: str, operation: str) -> List[str]:
    return [
        "sshpass",
        "-p",
        password,
        operation,
        "-o",
        "StrictHostKeyChecking=no",
    ]


def _remote_integration(variant: str, python_abi: str, wheel: Path,
                        result: Path) -> None:
    board_user = required_environment("BOARD_USER")
    board_ip = required_environment("BOARD_IP")
    password = required_environment("BOARD_PASSWORD_NVKS")
    target_trt_template = required_environment("WHEEL_TARGET_TRT_WHEEL")
    if "{python_abi}" not in target_trt_template:
        raise RuntimeError(
            "WHEEL_TARGET_TRT_WHEEL must contain the {python_abi} placeholder."
        )
    target_trt = target_trt_template.replace("{python_abi}", python_abi)
    target_model = required_environment("WHEEL_TARGET_MODEL_DIR")
    job_id = required_environment("CI_JOB_ID")
    target = f"{board_user}@{board_ip}"
    remote_root = os.environ.get("WHEEL_TARGET_WORK_DIR",
                                 f"/home/{board_user}")
    if not remote_root.startswith("/"):
        raise RuntimeError("WHEEL_TARGET_WORK_DIR must be an absolute path.")
    remote = str(PurePosixPath(remote_root) / f"edgellm-wheel-{job_id}")
    script = REPO_ROOT / "examples" / "python" / "installed_wheel_build_and_infer.py"
    ssh = _ssh_prefix(password, "ssh")
    scp = _ssh_prefix(password, "scp")
    run_checked([
        *ssh,
        target,
        f"rm -rf {shlex.quote(remote)} && mkdir -p {shlex.quote(remote)}",
    ])
    try:
        run_checked([*scp, str(wheel), str(script), f"{target}:{remote}/"])
        python_bin = _ABI_INTERPRETERS[python_abi]
        command = " && ".join([
            f"{python_bin} -m venv --without-pip {shlex.quote(remote + '/venv')}",
            (f"{python_bin} -m pip install --ignore-installed "
             f"--prefix {shlex.quote(remote + '/venv')} pip"),
            f"{shlex.quote(remote + '/venv/bin/python')} -m pip install {shlex.quote(target_trt)}",
            (f"{shlex.quote(remote + '/venv/bin/python')} -m pip install "
             f"--extra-index-url {shlex.quote(os.environ.get('WHEEL_EXTRA_INDEX_URL', 'https://pypi.nvidia.com'))} "
             f"{shlex.quote(remote + '/' + wheel.name)}"),
            (f"cd {shlex.quote(remote)} && "
             f"{shlex.quote(remote + '/venv/bin/python')} -I "
             f"{shlex.quote(remote + '/' + script.name)} "
             f"{shlex.quote(target_model)} {shlex.quote(remote + '/engine')} "
             f"--expected-variant {shlex.quote(variant)} "
             f"--result {shlex.quote(remote + '/result.json')}"),
        ])
        run_checked([*ssh, target, command])
        result.parent.mkdir(parents=True, exist_ok=True)
        run_checked([*scp, f"{target}:{remote}/result.json", str(result)])
    finally:
        subprocess.run(
            [*ssh, target, f"rm -rf {shlex.quote(remote)}"],
            check=False,
        )
    evidence = json.loads(result.read_text(encoding="utf-8"))
    evidence.update({
        "variant_id": variant,
        "python_abi": python_abi,
        "wheel": wheel.name,
        "wheel_sha256": sha256(wheel),
    })
    write_json(result, evidence)


def integration_ci() -> None:
    """Install one final wheel in a clean environment, build, and infer."""
    variant = required_environment("VARIANT")
    python_abi = required_environment("PYTHON_ABI")
    row = _variant_row(variant)
    environment_fields = (_REMOTE_INTEGRATION_ENVIRONMENT if row["ci_remote"]
                          else _LOCAL_INTEGRATION_ENVIRONMENT)
    _apply_variant_environment(row, environment_fields)
    wheel = _single_wheel(str(row["cpu_arch"]), python_abi)
    result = (REPO_ROOT / "artifacts" / "integration" /
              f"{variant}-{python_abi}.json")
    if os.environ.get("REMOTE_TARGET") == "1":
        _remote_integration(variant, python_abi, wheel, result)
    else:
        _local_integration(row, python_abi, wheel, result)


def _validate_integration_result(key: Tuple[str, str], value: Mapping[str,
                                                                      object],
                                 wheel: Path) -> None:
    if value.get("wheel") != wheel.name or value.get("wheel_sha256") != sha256(
            wheel):
        raise RuntimeError(
            f"Integration evidence for {key} references another wheel.")
    output_count = value.get("output_token_count")
    if not isinstance(output_count, int) or output_count < 1:
        raise RuntimeError(f"Integration evidence for {key} has no output.")
    output_text = value.get("output_text")
    if not isinstance(output_text, str) or not output_text.strip():
        raise RuntimeError(
            f"Integration evidence for {key} has no generated text.")


def integration_gate() -> None:
    """Require successful evidence for every variant and ABI."""
    matrix, rows = load_matrix(REPO_ROOT / "packaging" / "variants.toml")
    expected = {
        (str(row["variant_id"]), abi): row
        for row in rows
        for abi in matrix["qualified_python_abis"]
    }
    evidence_dir = REPO_ROOT / "artifacts" / "integration"
    found = {}
    for path in evidence_dir.glob("*.json"):
        if path.name == "gate.json":
            continue
        value = json.loads(path.read_text(encoding="utf-8"))
        key = (str(value.get("variant_id")), str(value.get("python_abi")))
        if key in found:
            raise RuntimeError(f"Duplicate integration evidence for {key}.")
        found[key] = value
    if set(found) != set(expected):
        raise RuntimeError("Incomplete integration evidence: "
                           f"missing={sorted(set(expected) - set(found))}, "
                           f"extra={sorted(set(found) - set(expected))}.")
    for key, value in found.items():
        row = expected[key]
        wheel = _single_wheel(str(row["cpu_arch"]), key[1])
        _validate_integration_result(key, value, wheel)
    write_json(
        REPO_ROOT / "artifacts" / "integration" / "gate.json",
        {
            "schema_version":
            1,
            "qualified_rows":
            len(found),
            "wheel_sha256":
            sorted({value["wheel_sha256"]
                    for value in found.values()}),
        },
    )
