/*
 * SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: LicenseRef-NvidiaProprietary
 *
 * NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
 * property and proprietary rights in and to this material, related
 * documentation and any modifications thereto. Any use, reproduction,
 * disclosure or distribution of this material and related documentation
 * without an express license agreement from NVIDIA CORPORATION or
 * its affiliates is strictly prohibited.
 */

#include "common/safetensors_loader/safetensorsLoader.h"
#include <cuda_fp16.h>
#include <cuda_runtime.h>
#include <gtest/gtest.h>
#include <vector>

// Helper functions for testing
float fp16ToFloat(uint16_t fp16)
{
    half h;
    std::memcpy(&h, &fp16, sizeof(half));
    return __half2float(h);
}

float bf16ToFloat(uint16_t bf16)
{
    uint32_t f32 = static_cast<uint32_t>(bf16) << 16;
    return *reinterpret_cast<float*>(&f32);
}

TEST(SafeTensorsLoadingTest, BasicLoading)
{
    std::string testFile = "../unittests/resources/test_safetensors.safetensors";
    drivellm::SafeTensorsLoader loader(testFile);

    // Load the file generated by Python script
    EXPECT_TRUE(loader.loadFromFileToGPU());

    // Get tensor info
    auto const& tensorInfo = loader.getSafeTensorsInfo();
    EXPECT_EQ(tensorInfo.size(), 2);

    // Verify tensor0
    auto const& tensor0 = tensorInfo.at("tensor0");
    EXPECT_EQ(tensor0.shape.size(), 2);
    EXPECT_EQ(tensor0.shape[0], 1);
    EXPECT_EQ(tensor0.shape[1], 5);
    EXPECT_EQ(tensor0.dtype, "F16");

    // Copy tensor0 data from GPU to CPU
    std::vector<uint16_t> tensor0Cpu(5);
    cudaMemcpy(tensor0Cpu.data(), tensor0.gpuPtr, 5 * sizeof(uint16_t), cudaMemcpyDeviceToHost);

    // Verify tensor0 values
    EXPECT_NEAR(fp16ToFloat(tensor0Cpu[0]), -2.0f, 1e-2);
    EXPECT_NEAR(fp16ToFloat(tensor0Cpu[1]), -1.25f, 1e-2);
    EXPECT_NEAR(fp16ToFloat(tensor0Cpu[2]), 0.0f, 1e-2);
    EXPECT_NEAR(fp16ToFloat(tensor0Cpu[3]), 1.1f, 1e-2);
    EXPECT_NEAR(fp16ToFloat(tensor0Cpu[4]), 2.0f, 1e-2);

    // Verify tensor1
    auto const& tensor1 = tensorInfo.at("tensor1");
    EXPECT_EQ(tensor1.shape.size(), 2);
    EXPECT_EQ(tensor1.shape[0], 1);
    EXPECT_EQ(tensor1.shape[1], 3);
    EXPECT_EQ(tensor1.dtype, "BF16");

    // Copy tensor1 data from GPU to CPU
    std::vector<uint16_t> tensor1Cpu(3);
    cudaMemcpy(tensor1Cpu.data(), tensor1.gpuPtr, 3 * sizeof(uint16_t), cudaMemcpyDeviceToHost);

    // Verify tensor1 values
    EXPECT_NEAR(bf16ToFloat(tensor1Cpu[0]), -3.8f, 1e-2);
    EXPECT_NEAR(bf16ToFloat(tensor1Cpu[1]), 0.0f, 1e-2);
    EXPECT_NEAR(bf16ToFloat(tensor1Cpu[2]), 2.7f, 1e-2);
}
